	AREA RESET,DATA,READONLY
	EXPORT __Vectors
__Vectors
	DCD	0x10001000; SP
	DCD Reset_Handler; Reset Vector
	ALIGN
	
	AREA mycode,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler
	
Reset_Handler
	LDR R0,=NUM
	LDRB R0,[R0]
	AND	R1,R0,#0x0F
	LSR R0,R0,#4
	MOV	R2,#0xA
	MLA R3,R0,R2,R1
	LDR	R4, =RESULT
	STRB R3,[R4]
STOP B STOP
NUM DCB 0x21
	AREA mydata,DATA,READWRITE
RESULT SPACE 1
	END