	AREA RESET,DATA,READONLY
	EXPORT __Vectors
__Vectors
	DCD	0x10001000; SP
	DCD Reset_Handler; Reset Vector
	ALIGN
	
	AREA mycode,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler
	
Reset_Handler
	LDR R0,=NUM
	LDRB R0,[R0]
	MOV R1,#0
	MOV R2,#10
UP	CMP R0,R2
	BLO	DONE
	SUB R0,R0,R2
	ADD R1,R1,#1
	B UP
DONE
	LSL R1,R1,#4
	ORR R1,R1,R0
	LDR	R3,=RESULT
	STRB	R1,[R3]
	BX	LR
	AREA input,DATA,READONLY
NUM DCB 0x15
	AREA mydata,DATA,READWRITE
RESULT SPACE 1
	END